### ISSUE TITLE
Radio mode can now be played 20 minutes after the stream is loaded

### ISSUE THREAD

**Issue by ddugovic** [c-rainbow/twitch-audio-web#23]
I'm not sure whether this release note means:
a) Radio mode can only initiate 20 minutes after the stream is loaded
b) Radio mode can only be used for 20 minutes, after which it automatically stops

I find Radio mode useful so I don't burn through my data cap watching unpopular 1080p channels, some of which lack ads:
https://arstechnica.com/tech-policy/2021/12/comcast-delays-data-caps-in-northeast-us-for-at-least-another-year/

**Comment by c-rainbow** [comment]
Hi @ddugovic , thanks for the feedback.

There was a bug that the radio mode can only start within the first 20 minutes after the page load.

If the radio mode started before that 20-minute mark, it continues until the end of the stream. However, if a user clicks the button to start the radio mode after 20 minutes, the button is disabled with error. The only workaround before 0.5.0 was to refresh the page.

In detail, the root cause of the bug was that Twitch's access token for the stream is only valid for 20 minutes. A new access token is obtained when the page is loaded, and the extension reused it for the radio mode.

It was not difficult to get a new one after expiration, but then I had a bigger issue that the radio mode is stuck for ~15 seconds before starting. Only recently I found out that the second issue was caused by advertisements (during which Twitch just sends a silent audio) and discovered a fix.

I can change the release note like this. Please let me know if you have any comments.
- Fixed a bug that the radio mode could not start after 20 minutes of page load.

**Comment by ddugovic** [comment]
Thanks for the detailed explanation!  That's perfect and I am glad to continue using this plugin.

(Sorry I lack additional feedback; out of curiosity I did look at other release notes and some commits, and I didn't see anything out of place.)
