### ISSUE TITLE
Porting Extension to Firefox

### ISSUE THREAD

**Issue by gmadharh** [c-rainbow/twitch-audio-web#9]
Hello, I had an idea to port this extension from Chrome to Firefox to make it more accessible. I've forked the repository and was wondering if you would allow me to make edits to the extension so it would work for Firefox as well.

Thank you for your time.

**Comment by c-rainbow** [comment]
Hi Gevin,

Firefox extension sounds like a great idea!

Yes, please fork and edit the code as you want.

I haven’t been working on it for a few months and there are some bugs. I am
sorry in advance if you encounter any issues while making a port. I’ll try
to fix them sometime this month.

Thanks!
Rainbow

**Comment by gmadharh** [comment]
I was running into issues trying to port the extension into firefox, it didn't seem to work when the radio button was clicked. No worries, I'll wait until you get to work on it and then give it another shot.

**Comment by c-rainbow** [comment]
Thank you for waiting. Could you describe what issues you ran into?

**Comment by c-rainbow** [comment]
I just released a new version (0.3.0). Can you pull the code and try again?

**Comment by zaxutic** [comment]
Hey, I've tried this out and turns out it actually *already works* in Firefox. You just need to build it with [web-ext](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/#testing-out-an-extension).

It works fine out of the box with `web-ext run` to open a Firefox window with the extension loaded, and with `web-ext build` to produce a package to load into Firefox directly in `about:debugging`. Everything works completely fine and there's no issues as far as I can tell (I tried it in Chrome first and I see no differences).

Looks like you should be able to package and [submit](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/) it without any further changes.

**Comment by gmadharh** [comment]
> Hey, I've tried this out and turns out it actually _already works_ in Firefox. You just need to build it with [web-ext](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/#testing-out-an-extension).
> 
> It works fine out of the box with `web-ext run` to open a Firefox window with the extension loaded, and with `web-ext build` to produce a package to load into Firefox directly in `about:debugging`. Everything works completely fine and there's no issues as far as I can tell (I tried it in Chrome first and I see no differences).
> 
> Looks like you should be able to package and [submit](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/) it without any further changes.

Hey thanks for commenting this, I'll get on this and do it as soon as I can.

**Comment by gmadharh** [comment]
Update,

I submitted the extension to the firefox add-on store and it was approved this morning. Here is the link:

https://addons.mozilla.org/en-CA/firefox/addon/twitch-audio-mode/
